// <auto-generated />
namespace CardMates.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newsID1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsID1));
        
        string IMigrationMetadata.Id
        {
            get { return "201506081034016_newsID1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
