// <auto-generated />
namespace CardMates.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newsID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsID));
        
        string IMigrationMetadata.Id
        {
            get { return "201506081015142_newsID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
