// <auto-generated />
namespace CardMates.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class img : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(img));
        
        string IMigrationMetadata.Id
        {
            get { return "201506071954483_img"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
