// <auto-generated />
namespace CardMates.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class full_news1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(full_news1));
        
        string IMigrationMetadata.Id
        {
            get { return "201504160749055_full_news1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
